name: Deploy StarsLab Site to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - "www/**"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: www
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: www/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5ccbd2ab14501cd236498638428d638d
          projectName: starslab-site
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
